//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiS_Solver_GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiS_Solver_GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -X 16519 -X 16517 -X 16513 -X 16511 -X 16507 -X 16505 -X 16501 -X 16499 -X 16495 -X 16493 -X 16489 -X 16487 -X 16483 -X 16481 .
        /// </summary>
        internal static string a10sExcludes {
            get {
                return ResourceManager.GetString("a10sExcludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -X 16518 -X 16515 -X 16512 -X 16509 -X 16506 -X 16503 -X 16500 -X 16497 -X 16494 -X 16491 -X 16488 -X 16485 -X 16482 -X 16479 .
        /// </summary>
        internal static string a11sExcludes {
            get {
                return ResourceManager.GetString("a11sExcludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -X 16516 -X 16510 -X 16504 -X 16498 -X 16492 -X 16486 -X 16480 -X 16478 -X 16477 -X 16476 -X 16475 -X 16474 -X 16473 -X 16472 -X 16471 -X 16470 -X 16469 -X 16468 -X 16467 -X 16466 -X 16465 .
        /// </summary>
        internal static string a12sExcludes {
            get {
                return ResourceManager.GetString("a12sExcludes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -X 16540 -X 16539 -X 16538 -X 16537 -X 16536 -X 16535 -X 16534 -X 16533 -X 16532 -X 16531 -X 16530 -X 16529 -X 16528 -X 16527 -X 16526 -X 16525 -X 16524 -X 16523 -X 16522 -X 16521 -X 16520 -X 16514 -X 16508 -X 16502 -X 16496 -X 16490 -X 16484 .
        /// </summary>
        internal static string a9sExcludes {
            get {
                return ResourceManager.GetString("a9sExcludes", resourceCulture);
            }
        }
    }
}
